DROP SEQUENCE SEQ_C;
DROP SEQUENCE SEQ_w;

DROP TABLE WORD CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;

CREATE SEQUENCE SEQ_C NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_W NOCYCLE NOCACHE;

CREATE TABLE CATEGORY
(
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE WORD
(
    NO NUMBER PRIMARY KEY
    , LENGTH NUMBER NOT NULL
    , WORD VARCHAR2(100) NOT NULL
    , CATEGORY_ID NUMBER
    , ACTIVE_WORD CHAR(1) DEFAULT 'Y' CHECK(ACTIVE_WORD IN('Y', 'N'))
    ,FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
)
;

INSERT INTO CATEGORY
(
    CATEGORY_ID
    , CATEGORY_NAME
)
VALUES
(
    SEQ_C.NEXTVAL
    , '과일'
);

INSERT INTO WORD
(
    NO
    , LENGTH
    , WORD
    , CATEGORY_ID
)
VALUES
(
    SEQ_W.NEXTVAL
    , '5'
    , 'APPLE'
    , 1
)
;
commit;